language: go

go:
  - 1.1
  - 1.2
  - tip

services:
  - redis-server

install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/deckarep/golang-set
  - go get github.com/garyburd/redigo/redis